import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  sectionP: { padding: 20, paddingHorizontal: 30 },
  sectionP20: { padding: 20 },
  contentContainer: {
    width: windowWidth,
    height: windowHeight * 0.75,
    borderBottomStartRadius: 15,
    marginTop: 40,
    backgroundColor: "#fff",
  },
  getStartedImage: {
    flex: 1,
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  getStartedHead: {
    fontSize: 42,
    textTransform: "uppercase",
    color: "#fff",
    textAlign: "center",
  },

  getStartedText: {
    color: "#fff",
    fontSize: 24,
    alignSelf: "center",
    textTransform: "uppercase",
  },
  greenShape: {
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderRightWidth: windowWidth + 200,
    borderTopWidth: windowHeight * (28 / 100),
    borderRightColor: "transparent",
    borderTopColor: "#dd4400",
  },
  loginHead: {
    textAlign: "center",
    fontSize: 23,
    marginVertical: 10,
    textTransform: "uppercase",
    fontWeight: "bold",
    color: "#dd4400",
    marginTop: -30,
  },
  loginBtn: {
    backgroundColor: "#dd4400",
    textAlign: "center",
    padding: 20,
    width: windowWidth * (80 / 100),
    alignSelf: "center",
    borderRadius: 25,
    fontSize: 16,
    color: "#fff",
    textTransform: "uppercase",
    marginTop: 20,
  },
  conBtn: {
    backgroundColor: "#dd4400",
    textAlign: "center",
    padding: 15,
    width: windowWidth * (44 / 100),
    alignSelf: "center",
    borderRadius: 25,
    fontSize: 16,
    color: "#fff",
    textTransform: "uppercase",
    marginTop: 20,
  },
  conBtn1: {
    backgroundColor: "lightblue",
    textAlign: "center",
    padding: 15,
    width: windowWidth * (44 / 100),
    alignSelf: "center",
    borderRadius: 25,
    fontSize: 16,
    color: "#fff",
    textTransform: "uppercase",
    marginTop: 20,
  },
  createBtn: {
    backgroundColor: "green",
    textAlign: "center",
    padding: 20,
    width: windowWidth * (80 / 100),
    alignSelf: "center",
    borderRadius: 25,
    fontSize: 16,
    color: "#fff",
    textTransform: "uppercase",
    marginVertical: 20,
  },
  continueBtn: {
    backgroundColor: "#dd4400",
    textAlign: "center",
    padding: 15,
    width: windowWidth * (90 / 100),
    alignSelf: "center",
    borderRadius: 15,
    fontSize: 16,
    color: "#fff",
    marginVertical: 20,
  },
  outBtn: {
    backgroundColor: "brown",
    textAlign: "center",
    padding: 15,
    width: windowWidth * (80 / 100),
    alignSelf: "center",
    borderRadius: 15,
    fontSize: 16,
    color: "#fff",
    marginTop: 30,
    marginBottom: 20,
  },
  loginForm: {
    marginHorizontal: 20,
    paddingHorizontal: 20,
    marginTop: 30,
  },
  appInput: {
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 12,
    marginBottom: 10,
    fontSize: 16,
    color: "#dd4400",
    borderWidth: 0.5,
  },
  pickerInput: {
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 2,
    marginBottom: 10,
    fontSize: 16,
    //color: "#dd4400",
    borderWidth: 0.5,
  },
  input: {
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    borderRadius: 25,
    paddingVertical: 15,
    marginBottom: 30,
    fontSize: 16,
    color: "#dd4400",
    borderWidth: 0.5,
  },
  appHead: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 10,
  },
  subHead: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    color: "#dd4400",
  },
  subHead2: {
    marginTop: 30,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#dd4400",
  },
  appForm: {
    padding: 20,
  },
  getCon: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
  },
  getBtn: {
    flex: 1,
    position: "absolute",
    bottom: 10,
    alignSelf: "center",
  },
  ovalCon: {
    width: windowWidth,
    height: windowHeight * (20 / 70),
  },
  greenBanner: {
    width: windowWidth,
    height: windowHeight * (23 / 100),
  },
  greyView: {
    width: windowWidth,
    paddingBottom: 15,
    backgroundColor: "#fff",
  },
  mtn10: {
    marginTop: -40,
  },
  avatar: {
    width: windowWidth * (32 / 100),
    height: windowWidth * (32 / 100),
    alignSelf: "center",
    borderRadius: 100,
    marginTop: -2,
  },
  p20: {
    padding: 20,
  },
  penHead: {
    marginBottom: 5,
    marginTop: 2,
    fontWeight: "bold",
    color: "#333",
  },
  penSub: { color: "#999", fontSize: 15 },
  penCon: {
    paddingTop: 10,
    paddingHorizontal: 50,
    paddingBottom: 50,
    backgroundColor: "#fff",
  },
  penOrg: {
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    alignContent: "center",
  },
  penLabel: {
    fontSize: 12,
    color: "#666",
  },
  orgLogo: {
    width: 28,
    height: 28,
    marginBottom: 10,
    marginRight: 5,
    marginTop: 2,
    borderRadius: 100,
  },
  greenView: {
    backgroundColor: "#dd4400",
    width: windowWidth,
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  plainView: {
    width: windowWidth,
    paddingTop: 50,
    paddingHorizontal: 15,
    paddingBottom: 10,
  },
  recentText: {
    color: "#dd4400",

    marginVertical: 10,
    textTransform: "uppercase",
    marginHorizontal: 20,
  },
  avatarHome: {
    width: 42,
    height: 42,
    borderRadius: 100,
  },
  greeting: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  greetSub: {
    color: "#ddd",
    fontSize: 15,
  },

  greetSub2: {
    color: "#ddd",
    fontSize: 12,
  },
  sumView: {
    borderRadius: 3,
    backgroundColor: "#cccccc3d",
    padding: 15,
    width: "65%",
  },
  gradView: {
    borderRadius: 20,
    padding: 15,
    width: "100%",
    backgroundColor: "#dd4400",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  balText: { color: "#eee", fontWeight: "bold" },
  balCon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gradIcon: {
    fontSize: 30,
    color: "#fff",
    backgroundColor: "#1bae19c2",
    borderRadius: 100,
    marginLeft: 8,
    padding: 5,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },

  walletView: {
    backgroundColor: "#fff",
    width: "30%",
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  totalPen: {
    color: "#fff",
    marginVertical: 5,
    fontWeight: "bold",
    fontSize: 20,
  },
  totalWallet: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 36,
  },
  ghc: {
    color: "#fff",
    alignSelf: "flex-end",
    marginLeft: 5,
    marginBottom: 7,
  },
  flexRow: { flexDirection: "row" },
  walletIcon: {
    fontSize: 24,
    color: "#dd4400",
  },
  walletAmount: {
    color: "gold",
    fontSize: 18,
    fontWeight: "bold",
    alignSelf: "center",
  },
  section: {
    marginHorizontal: 10,
  },
  recentCard: {
    width: "100%",
    borderWidth: 0.3,
    borderRadius: 3,
    borderColor: "#ccc",
    padding: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  topUpIcon: {
    fontSize: 22,
    color: "#dd4400",
  },
  redTopUpIcon: {
    fontSize: 22,
    color: "gold",
  },
  recentTitleText: {
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  recentTitleText2: {
    fontWeight: "bold",
    color: "#333",
    alignSelf: "flex-end",
    marginBottom: 5,
  },
  recentTitle: {
    width: "55%",
  },
  recentAmount: {
    width: "30%",
  },
  topBtn: {
    width: "100%",
    backgroundColor: "#dd4400",
    borderWidth: 1,
    borderColor: "#dd4400",
    paddingVertical: 13,
    textAlign: "center",
    borderRadius: 5,
    color: "#fff",
    fontSize: 16,
  },
  withBtn: {
    width: "100%",
    borderColor: "#dd4400",
    borderWidth: 1,
    paddingVertical: 13,
    textAlign: "center",
    borderRadius: 5,
    color: "#dd4400",
    fontSize: 16,
  },
  abRight: {
    position: "absolute",
    bottom: 10,
    right: 10,
    alignSelf: "flex-end",
  },
  editIcon: {
    fontSize: 36,
    color: "#fff",
    backgroundColor: "#dd4400",
    borderRadius: 100,
    padding: 15,
  },
  editText: {
    fontSize: 11,
    alignSelf: "center",
  },
  aboutCon: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  aboutHead: {
    textAlign: "center",
    fontSize: 18,
    textTransform: "uppercase",
    color: "#dd4400",
    marginBottom: 15,
  },
  aboutText: {
    marginHorizontal: 20,
    marginBottom: 30,
  },
  featureImage: {
    width: 84,
    height: 84,
    alignSelf: "center",
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: "#ddd",
  },
  aboutFeature: {
    width: "30%",
  },
  featureCon: {
    width: "100%",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  aboutFeatureText: {
    textAlign: "center",
    fontSize: 16,
  },
  btnCon: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 20,
    position: "absolute",
    bottom: 10,
  },
  btnCon2: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  gradBtnCon: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
    borderRadius: 10,
  },
  gradBtn: {
    width: "100%",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#dd4400",
    paddingVertical: 13,
    textAlign: "center",
    borderRadius: 25,
    color: "#dd4400",
    fontSize: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  logBtn: {
    width: "100%",
    backgroundColor: "#dd4400",
    borderWidth: 1,
    borderColor: "#dd4400",
    paddingVertical: 13,
    textAlign: "center",
    borderRadius: 50,
    color: "#fff",
    fontSize: 16,
  },
  shapeCon: {
    width: windowWidth,
    backgroundColor: "#dd4400",
    height: windowHeight * (25 / 100),
    justifyContent: "flex-end",
  },
  roundShape: {
    width: "100%",
    height: "60%",
    borderRadius: 50,
    marginBottom: -50,
  },
  modalHead: {
    fontSize: 14,
    textTransform: "uppercase",
    fontWeight: "bold",
    color: "#dd4400",
    marginBottom: 20,
  },
  modalLabel: {
    marginBottom: 8,
    color: "#888",
  },
  modalInput: {
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    borderRadius: 5,
    paddingVertical: 15,
    marginBottom: 15,
    fontSize: 18,
    color: "#666",
    borderWidth: 0.8,
    borderColor: "#dd4400",
  },
  modalBtn: {
    backgroundColor: "#dd4400",
    color: "#fff",
    fontSize: 16,
    width: "100%",
    alignSelf: "center",
    marginVertical: 20,
    borderRadius: 10,
    paddingVertical: 20,
    textAlign: "center",
    textTransform: "uppercase",
  },
  whiteView: {
    backgroundColor: "#fff",
    width: "100%",
    padding: 15,
    marginTop: 15,
    borderRadius: 10,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  moreOpacity: {
    position: "absolute",
    bottom: 15,
    alignSelf: "flex-end",
    right: 15,
  },
  moreIcon: {
    backgroundColor: "#dd4400",
    borderRadius: 100,
    color: "#fff",
    padding: 10,
    fontSize: 24,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  activityRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignContent: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    backgroundColor: "#eeeeee99",
    marginBottom: 15,
  },
  activityText: {
    textTransform: "uppercase",
    color: "#dd4400",
    alignSelf: "center",
  },
  activityIcon: {
    fontSize: 22,
    color: "#dd4400",
    opacity: 0.8,
    borderRadius: 100,
  },
  sortMenu: {
    backgroundColor: "#fff",
    position: "absolute",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 3,
    padding: 10,
    right: 30,
    top: 0,
    marginTop: -20,
  },
  faqView: {
    marginBottom: 20,
    backgroundColor: "#fff",
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 4,
  },
  faqHead: {
    color: "#dd4400",
    fontWeight: "bold",
    fontSize: 15,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#ddd",
  },
  faqExcerpt: {
    padding: 10,
    paddingTop: 5,
    paddingBottom: 0,
    color: "#888",
  },
  faqMore: {
    paddingHorizontal: 10,
    color: "#555",
  },
  faqBtn: {
    backgroundColor: "#dd4400",
    alignSelf: "flex-end",
    marginBottom: 10,
    marginRight: 10,
    paddingHorizontal: 15,
    paddingVertical: 8,
    color: "#fff",
    borderRadius: 20,
    fontSize: 11,
  },
  appPic: {
    width: windowWidth * 0.4,
    height: windowHeight * 0.25,
    alignSelf: "center",
    marginBottom: 10,
  },
  appFormpicText: {
    alignSelf: "center",
    marginBottom: 10,
    fontSize: 16,
  },
  uploadpicText: {
    backgroundColor: "#dd4400",
    padding: 10,
    color: "#fff",
    textAlign: "center",
    borderRadius: 5,
    marginBottom: 15,
  },
  uploadingBox: {
    width: windowWidth * 0.4,
    height: windowHeight * 0.25,
    backgroundColor: "#dd4400",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  uploadingText: {
    color: "#fff",
    alignSelf: "center",
  },
  half: {
    width: windowWidth * 0.44,
  },
  halveCon: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  formLabel: {
    color: "#444",
    marginLeft: 5,
    marginBottom: 3,
  },
  loadCon: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignContent: "center",
  },
  loadPic: {
    width: 240,
    height: 240,
    alignSelf: "center",
  },
});
